/* Generated By:JavaCC: Do not edit this line. lexico_csharpConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexico_csharpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 6;
  /** RegularExpression Id. */
  int LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int PRE_DEFINE = 8;
  /** RegularExpression Id. */
  int PRE_UNDEF = 9;
  /** RegularExpression Id. */
  int PRE_IF = 10;
  /** RegularExpression Id. */
  int PRE_ELIF = 11;
  /** RegularExpression Id. */
  int PRE_ELSE = 12;
  /** RegularExpression Id. */
  int PRE_ENDIF = 13;
  /** RegularExpression Id. */
  int PRE_LINE = 14;
  /** RegularExpression Id. */
  int PRE_ERROR = 15;
  /** RegularExpression Id. */
  int PRE_REGION = 16;
  /** RegularExpression Id. */
  int PRE_ENDREGION = 17;
  /** RegularExpression Id. */
  int PRE_NULLABLE = 18;
  /** RegularExpression Id. */
  int PRE_PRAGMA = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int NULL = 22;
  /** RegularExpression Id. */
  int DECORATED_DIGIT = 23;
  /** RegularExpression Id. */
  int INTEGER_SUFIX = 24;
  /** RegularExpression Id. */
  int BINARY_INTEGER = 25;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER = 26;
  /** RegularExpression Id. */
  int HEXADECIMAL_INTEGER = 27;
  /** RegularExpression Id. */
  int LITERAL_INTEGER = 28;
  /** RegularExpression Id. */
  int REAL_LITERAL = 29;
  /** RegularExpression Id. */
  int ABSTRACT = 30;
  /** RegularExpression Id. */
  int AS = 31;
  /** RegularExpression Id. */
  int BASE = 32;
  /** RegularExpression Id. */
  int BOOL = 33;
  /** RegularExpression Id. */
  int BREAK = 34;
  /** RegularExpression Id. */
  int BYTE = 35;
  /** RegularExpression Id. */
  int CASE = 36;
  /** RegularExpression Id. */
  int CATCH = 37;
  /** RegularExpression Id. */
  int CHAR = 38;
  /** RegularExpression Id. */
  int CHECKED = 39;
  /** RegularExpression Id. */
  int CLASS = 40;
  /** RegularExpression Id. */
  int CONST = 41;
  /** RegularExpression Id. */
  int CONTINUE = 42;
  /** RegularExpression Id. */
  int DECIMAL = 43;
  /** RegularExpression Id. */
  int KWDEFAULT = 44;
  /** RegularExpression Id. */
  int DELEGATE = 45;
  /** RegularExpression Id. */
  int DO = 46;
  /** RegularExpression Id. */
  int DOUBLE = 47;
  /** RegularExpression Id. */
  int ELSE = 48;
  /** RegularExpression Id. */
  int ENUM = 49;
  /** RegularExpression Id. */
  int EVENT = 50;
  /** RegularExpression Id. */
  int EXPLICIT = 51;
  /** RegularExpression Id. */
  int EXTERN = 52;
  /** RegularExpression Id. */
  int FINALLY = 53;
  /** RegularExpression Id. */
  int FIXED = 54;
  /** RegularExpression Id. */
  int FLOAT = 55;
  /** RegularExpression Id. */
  int FOR = 56;
  /** RegularExpression Id. */
  int FOREACH = 57;
  /** RegularExpression Id. */
  int GOTO = 58;
  /** RegularExpression Id. */
  int IF = 59;
  /** RegularExpression Id. */
  int IMPLICIT = 60;
  /** RegularExpression Id. */
  int IN = 61;
  /** RegularExpression Id. */
  int INT = 62;
  /** RegularExpression Id. */
  int INTERFACE = 63;
  /** RegularExpression Id. */
  int INTERNAL = 64;
  /** RegularExpression Id. */
  int IS = 65;
  /** RegularExpression Id. */
  int LOCK = 66;
  /** RegularExpression Id. */
  int LONG = 67;
  /** RegularExpression Id. */
  int NAMESPACE = 68;
  /** RegularExpression Id. */
  int NEW = 69;
  /** RegularExpression Id. */
  int OBJECT = 70;
  /** RegularExpression Id. */
  int OPERATOR = 71;
  /** RegularExpression Id. */
  int OUT = 72;
  /** RegularExpression Id. */
  int OVERRIDE = 73;
  /** RegularExpression Id. */
  int PARAMS = 74;
  /** RegularExpression Id. */
  int PRIVATE = 75;
  /** RegularExpression Id. */
  int PROTECTED = 76;
  /** RegularExpression Id. */
  int PUBLIC = 77;
  /** RegularExpression Id. */
  int READONLY = 78;
  /** RegularExpression Id. */
  int REF = 79;
  /** RegularExpression Id. */
  int RETURN = 80;
  /** RegularExpression Id. */
  int SBYTE = 81;
  /** RegularExpression Id. */
  int SEALED = 82;
  /** RegularExpression Id. */
  int SHORT = 83;
  /** RegularExpression Id. */
  int SIZEOF = 84;
  /** RegularExpression Id. */
  int STACKALLOC = 85;
  /** RegularExpression Id. */
  int STATIC = 86;
  /** RegularExpression Id. */
  int STRING = 87;
  /** RegularExpression Id. */
  int STRUCT = 88;
  /** RegularExpression Id. */
  int SWITCH = 89;
  /** RegularExpression Id. */
  int THIS = 90;
  /** RegularExpression Id. */
  int THROW = 91;
  /** RegularExpression Id. */
  int TRY = 92;
  /** RegularExpression Id. */
  int TYPEOF = 93;
  /** RegularExpression Id. */
  int UINT = 94;
  /** RegularExpression Id. */
  int ULONG = 95;
  /** RegularExpression Id. */
  int UNCHECKED = 96;
  /** RegularExpression Id. */
  int UNSAFE = 97;
  /** RegularExpression Id. */
  int USHORT = 98;
  /** RegularExpression Id. */
  int USING = 99;
  /** RegularExpression Id. */
  int VIRTUAL = 100;
  /** RegularExpression Id. */
  int VOID = 101;
  /** RegularExpression Id. */
  int VOLATILE = 102;
  /** RegularExpression Id. */
  int WHILE = 103;
  /** RegularExpression Id. */
  int ADD = 104;
  /** RegularExpression Id. */
  int ALIAS = 105;
  /** RegularExpression Id. */
  int ASCENDING = 106;
  /** RegularExpression Id. */
  int ASYNC = 107;
  /** RegularExpression Id. */
  int AWAIT = 108;
  /** RegularExpression Id. */
  int BY = 109;
  /** RegularExpression Id. */
  int DESCENDING = 110;
  /** RegularExpression Id. */
  int DYNAMIC = 111;
  /** RegularExpression Id. */
  int EQUALS = 112;
  /** RegularExpression Id. */
  int FROM = 113;
  /** RegularExpression Id. */
  int GET = 114;
  /** RegularExpression Id. */
  int GLOBAL = 115;
  /** RegularExpression Id. */
  int GROUP = 116;
  /** RegularExpression Id. */
  int INTO = 117;
  /** RegularExpression Id. */
  int JOIN = 118;
  /** RegularExpression Id. */
  int LET = 119;
  /** RegularExpression Id. */
  int NAMEOF = 120;
  /** RegularExpression Id. */
  int NOTNULL = 121;
  /** RegularExpression Id. */
  int ON = 122;
  /** RegularExpression Id. */
  int ORDERBY = 123;
  /** RegularExpression Id. */
  int PARTIAL = 124;
  /** RegularExpression Id. */
  int REMOVE = 125;
  /** RegularExpression Id. */
  int SELECT = 126;
  /** RegularExpression Id. */
  int SET = 127;
  /** RegularExpression Id. */
  int UNMANAGED = 128;
  /** RegularExpression Id. */
  int VALUE = 129;
  /** RegularExpression Id. */
  int VAR = 130;
  /** RegularExpression Id. */
  int WHEN = 131;
  /** RegularExpression Id. */
  int WHERE = 132;
  /** RegularExpression Id. */
  int YIELD = 133;
  /** RegularExpression Id. */
  int ASCII_ESCAPE = 134;
  /** RegularExpression Id. */
  int HEX_ESCAPE = 135;
  /** RegularExpression Id. */
  int OCTAL_ESCAPE = 136;
  /** RegularExpression Id. */
  int UNICODE4 = 137;
  /** RegularExpression Id. */
  int UNICODE8 = 138;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 139;
  /** RegularExpression Id. */
  int VERBATIM_STRING = 140;
  /** RegularExpression Id. */
  int SIMPLE_STRING = 141;
  /** RegularExpression Id. */
  int LITERAL_STRING = 142;
  /** RegularExpression Id. */
  int INTERPOLATED_SIMPLE_STRING = 143;
  /** RegularExpression Id. */
  int INTERPOLATED_VERBATIM_STRING = 144;
  /** RegularExpression Id. */
  int INTERPOLATED_LITERAL_STRING = 145;
  /** RegularExpression Id. */
  int PLUS = 146;
  /** RegularExpression Id. */
  int MINUS = 147;
  /** RegularExpression Id. */
  int MULT = 148;
  /** RegularExpression Id. */
  int DIV = 149;
  /** RegularExpression Id. */
  int ASSIGN = 150;
  /** RegularExpression Id. */
  int EQ = 151;
  /** RegularExpression Id. */
  int NEQ = 152;
  /** RegularExpression Id. */
  int LT = 153;
  /** RegularExpression Id. */
  int GT = 154;
  /** RegularExpression Id. */
  int LTE = 155;
  /** RegularExpression Id. */
  int GTE = 156;
  /** RegularExpression Id. */
  int AND = 157;
  /** RegularExpression Id. */
  int OR = 158;
  /** RegularExpression Id. */
  int NOT = 159;
  /** RegularExpression Id. */
  int BITAND = 160;
  /** RegularExpression Id. */
  int BITOR = 161;
  /** RegularExpression Id. */
  int BITXOR = 162;
  /** RegularExpression Id. */
  int BITNOT = 163;
  /** RegularExpression Id. */
  int QUESTION = 164;
  /** RegularExpression Id. */
  int COLON = 165;
  /** RegularExpression Id. */
  int NULL_COND = 166;
  /** RegularExpression Id. */
  int NULL_COALESCE = 167;
  /** RegularExpression Id. */
  int LAMBDA = 168;
  /** RegularExpression Id. */
  int INCR = 169;
  /** RegularExpression Id. */
  int DECR = 170;
  /** RegularExpression Id. */
  int ARROW = 171;
  /** RegularExpression Id. */
  int MOD = 172;
  /** RegularExpression Id. */
  int LPAREN = 173;
  /** RegularExpression Id. */
  int RPAREN = 174;
  /** RegularExpression Id. */
  int LBRACE = 175;
  /** RegularExpression Id. */
  int RBRACE = 176;
  /** RegularExpression Id. */
  int LBRACKET = 177;
  /** RegularExpression Id. */
  int RBRACKET = 178;
  /** RegularExpression Id. */
  int COMMA = 179;
  /** RegularExpression Id. */
  int DOT = 180;
  /** RegularExpression Id. */
  int SEMI = 181;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 182;
  /** RegularExpression Id. */
  int ELLIPSIS = 183;
  /** RegularExpression Id. */
  int SIMPLE_ID = 184;
  /** RegularExpression Id. */
  int ESCAPED_ID = 185;
  /** RegularExpression Id. */
  int ID = 186;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<COMMENT_BLOCK>",
    "<LINE_COMMENT>",
    "\"#define\"",
    "\"#undef\"",
    "\"#if\"",
    "\"#elif\"",
    "\"#else\"",
    "\"#endif\"",
    "\"#line\"",
    "\"#error\"",
    "\"#region\"",
    "\"#endregion\"",
    "\"#nullable\"",
    "\"#pragma\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<DECORATED_DIGIT>",
    "<INTEGER_SUFIX>",
    "<BINARY_INTEGER>",
    "<DECIMAL_INTEGER>",
    "<HEXADECIMAL_INTEGER>",
    "<LITERAL_INTEGER>",
    "<REAL_LITERAL>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"add\"",
    "\"alias\"",
    "\"ascending\"",
    "\"async\"",
    "\"await\"",
    "\"by\"",
    "\"descending\"",
    "\"dynamic\"",
    "\"equals\"",
    "\"from\"",
    "\"get\"",
    "\"global\"",
    "\"group\"",
    "\"into\"",
    "\"join\"",
    "\"let\"",
    "\"nameof\"",
    "\"notnull\"",
    "\"on\"",
    "\"orderby\"",
    "\"partial\"",
    "\"remove\"",
    "\"select\"",
    "\"set\"",
    "\"unmanaged\"",
    "\"value\"",
    "\"var\"",
    "\"when\"",
    "\"where\"",
    "\"yield\"",
    "<ASCII_ESCAPE>",
    "<HEX_ESCAPE>",
    "<OCTAL_ESCAPE>",
    "<UNICODE4>",
    "<UNICODE8>",
    "<CHAR_LITERAL>",
    "<VERBATIM_STRING>",
    "<SIMPLE_STRING>",
    "<LITERAL_STRING>",
    "<INTERPOLATED_SIMPLE_STRING>",
    "<INTERPOLATED_VERBATIM_STRING>",
    "<INTERPOLATED_LITERAL_STRING>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"?.\"",
    "\"??\"",
    "\"=>\"",
    "\"++\"",
    "\"--\"",
    "\"->\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"::\"",
    "\"...\"",
    "<SIMPLE_ID>",
    "<ESCAPED_ID>",
    "<ID>",
  };

}
