/* Generated By:JavaCC: Do not edit this line. lexico_csharpTokenManager.java */
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.HashMap;

/** Token Manager. */
public class lexico_csharpTokenManager implements lexico_csharpConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffffff0e00L) != 0L || (active1 & 0x3ffffffL) != 0L)
         {
            jjmatchedKind = 90;
            return 9;
         }
         if ((active1 & 0x2000000000L) != 0L)
            return 40;
         return -1;
      case 1:
         if ((active0 & 0xfff05ffcfffd0e00L) != 0L || (active1 & 0x3ffffffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 90;
               jjmatchedPos = 1;
            }
            return 9;
         }
         if ((active0 & 0xfa00300020000L) != 0L)
            return 9;
         return -1;
      case 2:
         if ((active0 & 0xfb7053fefffd0e00L) != 0L || (active1 & 0x3ffbffdL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 90;
               jjmatchedPos = 2;
            }
            return 9;
         }
         if ((active0 & 0x4870c0000000000L) != 0L || (active1 & 0x4002L) != 0L)
            return 9;
         return -1;
      case 3:
         if ((active0 & 0xfb464bf2fe910400L) != 0L || (active1 & 0x37eaffdL) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 3;
            return 9;
         }
         if ((active0 & 0x30100c016c0a00L) != 0L || (active1 & 0x811000L) != 0L)
            return 9;
         return -1;
      case 4:
         if ((active0 & 0xfb4648e2f2010000L) != 0L || (active1 & 0x15c8fd5L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 4;
            return 9;
         }
         if ((active0 & 0x3100c900400L) != 0L || (active1 & 0x2222028L) != 0L)
            return 9;
         return -1;
      case 5:
         if ((active0 & 0x6a4648a0f2010000L) != 0L || (active1 & 0x1440081L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 5;
            return 9;
         }
         if ((active0 & 0x9100004200000000L) != 0L || (active1 & 0x188f54L) != 0L)
            return 9;
         return -1;
      case 6:
         if ((active0 & 0x4a46402090010000L) != 0L || (active1 & 0x1040081L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 6;
            return 9;
         }
         if ((active0 & 0x2000088062000000L) != 0L || (active1 & 0x400000L) != 0L)
            return 9;
         return -1;
      case 7:
         if ((active0 & 0x4042000000000000L) != 0L || (active1 & 0x40080L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 7;
            return 9;
         }
         if ((active0 & 0xa04402090010000L) != 0L || (active1 & 0x1000001L) != 0L)
            return 9;
         return -1;
      case 8:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 90;
            jjmatchedPos = 8;
            return 9;
         }
         if ((active0 & 0x4042000000000000L) != 0L || (active1 & 0x40000L) != 0L)
            return 9;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 111;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10000000000L, 0x0L);
      case 35:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1ff80L);
      case 38:
         jjmatchedKind = 112;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 124);
      case 41:
         return jjStopAtPos(0, 125);
      case 42:
         return jjStopAtPos(0, 100);
      case 43:
         jjmatchedKind = 98;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 130);
      case 45:
         jjmatchedKind = 99;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc00000000000000L, 0x0L);
      case 46:
         jjmatchedKind = 131;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x40L);
      case 47:
         return jjStartNfaWithStates_0(0, 101, 40);
      case 58:
         jjmatchedKind = 117;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20L);
      case 59:
         return jjStopAtPos(0, 132);
      case 60:
         jjmatchedKind = 105;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000L, 0x0L);
      case 61:
         jjmatchedKind = 102;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100008000000000L, 0x0L);
      case 62:
         jjmatchedKind = 106;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000L, 0x0L);
      case 63:
         jjmatchedKind = 116;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc0000000000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 128);
      case 93:
         return jjStopAtPos(0, 129);
      case 94:
         return jjStopAtPos(0, 114);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x30000L, 0x0L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x3c0000L, 0x0L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1fc00000L, 0x0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3e0000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x7c00000000L, 0x0L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf8000000400L, 0x0L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xfe00000000000L, 0x0L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x30000000000000L, 0x0L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0xc0000000000800L, 0x0L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0xf00000000000000L, 0x0L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0xf000000000000000L, 0x0L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xff8L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x200L, 0xf000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3f0000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1c00000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 126);
      case 124:
         jjmatchedKind = 113;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 127);
      case 126:
         return jjStopAtPos(0, 115);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 109);
         break;
      case 43:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 121);
         break;
      case 45:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 122);
         break;
      case 46:
         if ((active1 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 118);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x40L);
      case 58:
         if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(1, 133);
         break;
      case 61:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 103);
         else if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         else if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         break;
      case 62:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 120);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 123);
         break;
      case 63:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 119);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1040000000c40400L, active1, 0L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000010000L, active1, 0x8L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x8000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000e0000000L, active1, 0x17L, active2, 0x2b00L);
      case 102:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 45, 9);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000000L, active1, 0x2003020L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000000000L, active1, 0x410040L, active2, 0x80L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20404000000L, active1, 0x20000L, active2, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      case 110:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x7000800000000L, active1, 0xc0000L, active2, 0L);
      case 111:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x301c0218080000L, active1, 0x1800000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000000L, active1, 0L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000000000100200L, active1, 0x4000L, active2, 0x400L);
      case 115:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 9);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 51, 9);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x300000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x780L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8400000000000800L, active1, 0L, active2, 0x10000L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x800001000000000L, active1, 0L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800L, active2, 0x4000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000000000L, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000L, active1, 0x8000L, active2, 0L);
      case 124:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 110);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active2 & 0x40L) != 0L)
            return jjStopAtPos(2, 134);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000000L, active1, 0x191L, active2, 0x4000L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000020000000L, active1, 0x40000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0xa00001002100000L, active1, 0L, active2, 0x8400L);
      case 102:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 65, 9);
         else if ((active2 & 0x80L) != 0L)
            return jjStopAtPos(2, 135);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000000L, active1, 0x2a01800L, active2, 0x1000L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000c00L, active1, 0x1000000L, active2, 0x100L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x20008018000000L, active1, 0x10000L, active2, 0x10a00L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000020000080000L, active1, 0x20020L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x402000000000L, active1, 0x8000L, active2, 0L);
      case 114:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x1000080000000000L, active1, 0x402600L, active2, 0x2000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x400450000L, active1, 0x80000L, active2, 0L);
      case 116:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 58, 9);
         return jjMoveStringLiteralDfa3_0(active0, 0x6104000a00000L, active1, 0x4L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0xa00000200L, active1, 0L, active2, 0L);
      case 119:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 55, 9);
         break;
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 78, 9);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8L, active2, 0L);
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000028040100000L, active1, 0x1080000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x2800000L, active1, 0x80L, active2, 0L);
      case 100:
         if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 87, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1L, active2, 0x10a00L);
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(3, 9, 9);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 9);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 9);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 22, 9);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0x146094080000000L, active1, 0x8040L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x8000L);
      case 103:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 53, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0L, active2, 0x400L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0x200L, active2, 0L);
      case 107:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 9);
         break;
      case 108:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 9);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000402000000000L, active1, 0x2000010L, active2, 0L);
      case 109:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 9);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0x220000L, active2, 0x1000L);
      case 111:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x102000L, active2, 0L);
      case 114:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0xa00000000000000L, active1, 0x20L, active2, 0x6000L);
      case 115:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 76, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0xc000400L, active1, 0L, active2, 0x100L);
      case 116:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 80, 9);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000010010000L, active1, 0x400908L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x404L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x2200080000000000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0xc00L, active2, 0L);
      case 100:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 9);
         break;
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 9);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(4, 67, 9);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 89, 9);
         else if ((active2 & 0x100L) != 0L)
            return jjStopAtPos(4, 136);
         else if ((active2 & 0x1000L) != 0L)
            return jjStopAtPos(4, 140);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0x40010L, active2, 0x10000L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000L, active2, 0L);
      case 103:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 81, 9);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 85, 9);
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L, active1, 0L, active2, 0L);
      case 104:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 9);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000402010000000L, active1, 0x100L, active2, 0x8600L);
      case 107:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 20, 9);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L, active1, 0x80L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8200000000L, active1, 0L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000020000000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200L, active2, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8041L, active2, 0x2000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x806004000010000L, active1, 0x100004L, active2, 0x800L);
      case 115:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 9);
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 9);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 9);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 41, 9);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 69, 9);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x1000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L, active1, 0x400000L, active2, 0L);
      case 119:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 77, 9);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0xa0010000L, active1, 0x400080L, active2, 0L);
      case 99:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 63, 9);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 72, 9);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000482000000000L, active1, 0x40000L, active2, 0L);
      case 100:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 9);
         break;
      case 101:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 9);
         else if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 83, 9);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000L, active1, 0L, active2, 0x800L);
      case 102:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(5, 70, 9);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 79, 9);
         else if ((active2 & 0x200L) != 0L)
            return jjStopAtPos(5, 137);
         else if ((active2 & 0x10000L) != 0L)
            return jjStopAtPos(5, 144);
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L, active1, 0L, active2, 0L);
      case 103:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(5, 73, 9);
         break;
      case 104:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 75, 9);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000000L, active1, 0x1000000L, active2, 0x4000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x8040000000L, active1, 0L, active2, 0L);
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 9);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 66, 9);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000010000000L, active1, 0x1L, active2, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0L, active2, 0x400L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active2 & 0x2000L) != 0L)
            return jjStopAtPos(5, 141);
         break;
      case 115:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 60, 9);
         break;
      case 116:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 56, 9);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 74, 9);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 84, 9);
         return jjMoveStringLiteralDfa6_0(active0, 0x2200000000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x46000000000000L, active1, 0L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L, active1, 0L, active2, 0L);
      case 100:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 9);
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000000L, active1, 0L, active2, 0L);
      case 101:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 61, 9);
         else if ((active2 & 0x8000L) != 0L)
            return jjStopAtPos(6, 143);
         break;
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x800L);
      case 104:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 43, 9);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x402000000000L, active1, 0L, active2, 0L);
      case 107:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L, active2, 0L);
      case 108:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 9);
         else if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 86, 9);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x1000081L, active2, 0L);
      case 110:
         if ((active2 & 0x400L) != 0L)
            return jjStopAtPos(6, 138);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L, active1, 0L, active2, 0L);
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 9);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000080000000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 39, 9);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x42000000000000L, active1, 0L, active2, 0L);
      case 101:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 9);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 31, 9);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 59, 9);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(7, 88, 9);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000000L, active1, 0x40000L, active2, 0L);
      case 103:
         if ((active2 & 0x4000L) != 0L)
            return jjStopAtPos(7, 142);
         break;
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0L, active2, 0x800L);
      case 108:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 50, 9);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80L, active2, 0L);
      case 114:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 9);
         break;
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 9);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 37, 9);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 46, 9);
         break;
      case 121:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(7, 64, 9);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 62, 9);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 82, 9);
         break;
      case 101:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 49, 9);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 54, 9);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x80L, active2, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1, active2);
      return 9;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(9, 71, 9);
         break;
      case 110:
         if ((active2 & 0x800L) != 0L)
            return jjStopAtPos(9, 139);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1, active2);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 68;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 40:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 47;
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(41, 42);
                  if (curChar == 47)
                  {
                     if (kind > 7)
                        kind = 7;
                     jjCheckNAdd(46);
                  }
                  break;
               case 0:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAddStates(5, 11);
                  }
                  else if (curChar == 47)
                     jjAddStates(12, 14);
                  else if (curChar == 34)
                     jjCheckNAddStates(15, 18);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAddStates(0, 4);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 10:
                  if (curChar == 34)
                     jjCheckNAddStates(19, 21);
                  break;
               case 11:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(19, 21);
                  break;
               case 12:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 13:
                  if (curChar == 34 && kind > 96)
                     kind = 96;
                  break;
               case 15:
                  if (curChar == 34)
                     jjCheckNAddStates(15, 18);
                  break;
               case 16:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 17:
                  if (curChar == 34 && kind > 97)
                     kind = 97;
                  break;
               case 19:
                  if ((0x1008400000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(22, 26);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(27);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 36:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 31);
                  break;
               case 37:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(32, 36);
                  break;
               case 38:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 39:
                  if (curChar == 47)
                     jjAddStates(12, 14);
                  break;
               case 41:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 42:
                  if (curChar == 42)
                     jjAddStates(37, 38);
                  break;
               case 43:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 44:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 45:
                  if (curChar != 47)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(46);
                  break;
               case 46:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(46);
                  break;
               case 47:
                  if (curChar != 47)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(48);
                  break;
               case 48:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(48);
                  break;
               case 49:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 50:
                  if (curChar != 48)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(5, 11);
                  break;
               case 52:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 53:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(39, 43);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjAddStates(44, 48);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 90)
                        kind = 90;
                     jjCheckNAdd(9);
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 2:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjAddStates(49, 51);
                  break;
               case 3:
                  if ((0x100000001000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 4:
                  if (curChar == 76 && kind > 13)
                     kind = 13;
                  break;
               case 5:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 108 && kind > 13)
                     kind = 13;
                  break;
               case 7:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
               case 9:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 90)
                     kind = 90;
                  jjCheckNAdd(9);
                  break;
               case 11:
                  jjAddStates(19, 21);
                  break;
               case 14:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 16:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 18:
                  if (curChar == 92)
                     jjAddStates(52, 53);
                  break;
               case 19:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 20:
                  if (curChar == 92)
                     jjAddStates(54, 56);
                  break;
               case 21:
                  if (curChar == 120)
                     jjCheckNAdd(22);
                  break;
               case 22:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(22, 26);
                  break;
               case 23:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
               case 35:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(27);
                  break;
               case 27:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(15, 18);
                  break;
               case 28:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 41:
               case 43:
                  jjCheckNAddTwoStates(41, 42);
                  break;
               case 46:
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (kind > 8)
                     kind = 8;
                  jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 51:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjAddStates(57, 59);
                  break;
               case 55:
                  if ((0x100000001000L & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 56:
                  if (curChar == 76 && kind > 14)
                     kind = 14;
                  break;
               case 57:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 108 && kind > 14)
                     kind = 14;
                  break;
               case 59:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(61);
                  break;
               case 61:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddStates(44, 48);
                  break;
               case 62:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAddStates(60, 62);
                  break;
               case 63:
                  if ((0x100000001000L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 64:
                  if (curChar == 76 && kind > 15)
                     kind = 15;
                  break;
               case 65:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 108 && kind > 15)
                     kind = 15;
                  break;
               case 67:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(19, 21);
                  break;
               case 16:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(15, 18);
                  break;
               case 41:
               case 43:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 46:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjstateSet[jjnewStateCnt++] = 48;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 68 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 2, 3, 5, 7, 51, 53, 54, 55, 57, 59, 60, 40, 45, 49, 16, 
   17, 18, 20, 11, 12, 13, 16, 22, 17, 18, 20, 16, 17, 18, 20, 37, 
   16, 38, 17, 18, 20, 43, 44, 53, 54, 55, 57, 59, 61, 62, 63, 65, 
   67, 3, 5, 7, 19, 36, 21, 23, 28, 55, 57, 59, 63, 65, 67, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, "\164\162\165\145", 
"\146\141\154\163\145", "\156\165\154\154", null, null, null, null, 
"\141\142\163\164\162\141\143\164", "\141\163", "\142\141\163\145", "\142\157\157\154", "\142\162\145\141\153", 
"\142\171\164\145", "\143\141\163\145", "\143\141\164\143\150", "\143\150\141\162", 
"\143\150\145\143\153\145\144", "\143\154\141\163\163", "\143\157\156\163\164", 
"\143\157\156\164\151\156\165\145", "\144\145\143\151\155\141\154", "\144\145\146\141\165\154\164", 
"\144\145\154\145\147\141\164\145", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\145\156\165\155", "\145\166\145\156\164", "\145\170\160\154\151\143\151\164", 
"\145\170\164\145\162\156", "\146\151\156\141\154\154\171", "\146\151\170\145\144", 
"\146\154\157\141\164", "\146\157\162", "\146\157\162\145\141\143\150", "\147\157\164\157", 
"\151\146", "\151\155\160\154\151\143\151\164", "\151\156", "\151\156\164", 
"\151\156\164\145\162\146\141\143\145", "\151\156\164\145\162\156\141\154", "\151\163", "\154\157\143\153", 
"\154\157\156\147", "\156\141\155\145\163\160\141\143\145", "\156\145\167", 
"\157\142\152\145\143\164", "\157\160\145\162\141\164\157\162", "\157\165\164", 
"\157\166\145\162\162\151\144\145", "\160\141\162\141\155\163", "\160\162\151\166\141\164\145", 
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\162\145\141\144\157\156\154\171", 
"\162\145\146", "\162\145\164\165\162\156", "\163\142\171\164\145", 
"\163\145\141\154\145\144", "\163\150\157\162\164", "\163\151\172\145\157\146", 
"\163\164\141\143\153\141\154\154\157\143", "\163\164\141\164\151\143", "\163\164\162\151\156\147", 
"\163\164\162\165\143\164", "\163\167\151\164\143\150", "\164\150\151\163", "\164\150\162\157\167", 
"\164\162\171", "\164\171\160\145\157\146", "\165\151\156\164", "\165\154\157\156\147", 
"\165\156\143\150\145\143\153\145\144", "\165\156\163\141\146\145", "\165\163\150\157\162\164", 
"\165\163\151\156\147", "\166\151\162\164\165\141\154", "\166\157\151\144", 
"\166\157\154\141\164\151\154\145", "\167\150\151\154\145", null, null, null, null, null, null, null, null, "\53", 
"\55", "\52", "\57", "\75", "\75\75", "\41\75", "\74", "\76", "\74\75", "\76\75", 
"\46\46", "\174\174", "\41", "\46", "\174", "\136", "\176", "\77", "\72", "\77\56", 
"\77\77", "\75\76", "\53\53", "\55\55", "\55\76", "\50", "\51", "\173", "\175", "\133", 
"\135", "\54", "\56", "\73", "\72\72", "\56\56\56", "\43\151\146", 
"\43\145\154\163\145", "\43\145\156\144\151\146", "\43\162\145\147\151\157\156", 
"\43\145\156\144\162\145\147\151\157\156", "\43\154\151\156\145", "\43\145\162\162\157\162", 
"\43\167\141\162\156\151\156\147", "\43\144\145\146\151\156\145", "\43\165\156\144\145\146", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xfffffffffffffe01L, 0xffffffff07ffffffL, 0x1ffffL, 
};
static final long[] jjtoSkip = {
   0x1feL, 0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[68];
static private final int[] jjstateSet = new int[136];
static protected char curChar;
/** Constructor. */
public lexico_csharpTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public lexico_csharpTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 68; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
