/* Generated By:JavaCC: Do not edit this line. lexico_csharpConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexico_csharpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 6;
  /** RegularExpression Id. */
  int LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int PRE_IF = 8;
  /** RegularExpression Id. */
  int PRE_ELSE = 9;
  /** RegularExpression Id. */
  int PRE_ENDIF = 10;
  /** RegularExpression Id. */
  int PRE_REGION = 11;
  /** RegularExpression Id. */
  int PRE_ENDREGION = 12;
  /** RegularExpression Id. */
  int PRE_LINE = 13;
  /** RegularExpression Id. */
  int PRE_ERROR = 14;
  /** RegularExpression Id. */
  int PRE_WARNING = 15;
  /** RegularExpression Id. */
  int PRE_DEFINE = 16;
  /** RegularExpression Id. */
  int PRE_UNDEF = 17;
  /** RegularExpression Id. */
  int TRUE = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int NULL = 20;
  /** RegularExpression Id. */
  int BINARY_INTEGER = 21;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER = 22;
  /** RegularExpression Id. */
  int HEXADECIMAL_INTEGER = 23;
  /** RegularExpression Id. */
  int ABSTRACT = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int BASE = 26;
  /** RegularExpression Id. */
  int BOOL = 27;
  /** RegularExpression Id. */
  int BREAK = 28;
  /** RegularExpression Id. */
  int BYTE = 29;
  /** RegularExpression Id. */
  int CASE = 30;
  /** RegularExpression Id. */
  int CATCH = 31;
  /** RegularExpression Id. */
  int CHAR = 32;
  /** RegularExpression Id. */
  int CHECKED = 33;
  /** RegularExpression Id. */
  int CLASS = 34;
  /** RegularExpression Id. */
  int CONST = 35;
  /** RegularExpression Id. */
  int CONTINUE = 36;
  /** RegularExpression Id. */
  int DECIMAL = 37;
  /** RegularExpression Id. */
  int KWDEFAULT = 38;
  /** RegularExpression Id. */
  int DELEGATE = 39;
  /** RegularExpression Id. */
  int DO = 40;
  /** RegularExpression Id. */
  int DOUBLE = 41;
  /** RegularExpression Id. */
  int ELSE = 42;
  /** RegularExpression Id. */
  int ENUM = 43;
  /** RegularExpression Id. */
  int EVENT = 44;
  /** RegularExpression Id. */
  int EXPLICIT = 45;
  /** RegularExpression Id. */
  int EXTERN = 46;
  /** RegularExpression Id. */
  int FINALLY = 47;
  /** RegularExpression Id. */
  int FIXED = 48;
  /** RegularExpression Id. */
  int FLOAT = 49;
  /** RegularExpression Id. */
  int FOR = 50;
  /** RegularExpression Id. */
  int FOREACH = 51;
  /** RegularExpression Id. */
  int GOTO = 52;
  /** RegularExpression Id. */
  int IF = 53;
  /** RegularExpression Id. */
  int IMPLICIT = 54;
  /** RegularExpression Id. */
  int IN = 55;
  /** RegularExpression Id. */
  int INT = 56;
  /** RegularExpression Id. */
  int INTERFACE = 57;
  /** RegularExpression Id. */
  int INTERNAL = 58;
  /** RegularExpression Id. */
  int IS = 59;
  /** RegularExpression Id. */
  int LOCK = 60;
  /** RegularExpression Id. */
  int LONG = 61;
  /** RegularExpression Id. */
  int NAMESPACE = 62;
  /** RegularExpression Id. */
  int NEW = 63;
  /** RegularExpression Id. */
  int OBJECT = 64;
  /** RegularExpression Id. */
  int OPERATOR = 65;
  /** RegularExpression Id. */
  int OUT = 66;
  /** RegularExpression Id. */
  int OVERRIDE = 67;
  /** RegularExpression Id. */
  int PARAMS = 68;
  /** RegularExpression Id. */
  int PRIVATE = 69;
  /** RegularExpression Id. */
  int PROTECTED = 70;
  /** RegularExpression Id. */
  int PUBLIC = 71;
  /** RegularExpression Id. */
  int READONLY = 72;
  /** RegularExpression Id. */
  int REF = 73;
  /** RegularExpression Id. */
  int RETURN = 74;
  /** RegularExpression Id. */
  int SBYTE = 75;
  /** RegularExpression Id. */
  int SEALED = 76;
  /** RegularExpression Id. */
  int SHORT = 77;
  /** RegularExpression Id. */
  int SIZEOF = 78;
  /** RegularExpression Id. */
  int STACKALLOC = 79;
  /** RegularExpression Id. */
  int STATIC = 80;
  /** RegularExpression Id. */
  int STRING = 81;
  /** RegularExpression Id. */
  int STRUCT = 82;
  /** RegularExpression Id. */
  int SWITCH = 83;
  /** RegularExpression Id. */
  int THIS = 84;
  /** RegularExpression Id. */
  int THROW = 85;
  /** RegularExpression Id. */
  int TRY = 86;
  /** RegularExpression Id. */
  int TYPEOF = 87;
  /** RegularExpression Id. */
  int UINT = 88;
  /** RegularExpression Id. */
  int ULONG = 89;
  /** RegularExpression Id. */
  int UNCHECKED = 90;
  /** RegularExpression Id. */
  int UNSAFE = 91;
  /** RegularExpression Id. */
  int USHORT = 92;
  /** RegularExpression Id. */
  int USING = 93;
  /** RegularExpression Id. */
  int VIRTUAL = 94;
  /** RegularExpression Id. */
  int VOID = 95;
  /** RegularExpression Id. */
  int VOLATILE = 96;
  /** RegularExpression Id. */
  int WHILE = 97;
  /** RegularExpression Id. */
  int SIMPLE_ID = 98;
  /** RegularExpression Id. */
  int ESCAPED_ID = 99;
  /** RegularExpression Id. */
  int ID = 100;
  /** RegularExpression Id. */
  int ASCII_ESCAPE = 101;
  /** RegularExpression Id. */
  int HEX_ESCAPE = 102;
  /** RegularExpression Id. */
  int OCTAL_ESCAPE = 103;
  /** RegularExpression Id. */
  int UNICODE4 = 104;
  /** RegularExpression Id. */
  int UNICODE8 = 105;
  /** RegularExpression Id. */
  int VERBATIM_STRING = 106;
  /** RegularExpression Id. */
  int STRING_LITERAL = 107;
  /** RegularExpression Id. */
  int PLUS = 108;
  /** RegularExpression Id. */
  int MINUS = 109;
  /** RegularExpression Id. */
  int MULT = 110;
  /** RegularExpression Id. */
  int DIV = 111;
  /** RegularExpression Id. */
  int ASSIGN = 112;
  /** RegularExpression Id. */
  int EQ = 113;
  /** RegularExpression Id. */
  int NEQ = 114;
  /** RegularExpression Id. */
  int LT = 115;
  /** RegularExpression Id. */
  int GT = 116;
  /** RegularExpression Id. */
  int LTE = 117;
  /** RegularExpression Id. */
  int GTE = 118;
  /** RegularExpression Id. */
  int AND = 119;
  /** RegularExpression Id. */
  int OR = 120;
  /** RegularExpression Id. */
  int NOT = 121;
  /** RegularExpression Id. */
  int BITAND = 122;
  /** RegularExpression Id. */
  int BITOR = 123;
  /** RegularExpression Id. */
  int BITXOR = 124;
  /** RegularExpression Id. */
  int BITNOT = 125;
  /** RegularExpression Id. */
  int QUESTION = 126;
  /** RegularExpression Id. */
  int COLON = 127;
  /** RegularExpression Id. */
  int NULL_COND = 128;
  /** RegularExpression Id. */
  int NULL_COALESCE = 129;
  /** RegularExpression Id. */
  int LAMBDA = 130;
  /** RegularExpression Id. */
  int INCR = 131;
  /** RegularExpression Id. */
  int DECR = 132;
  /** RegularExpression Id. */
  int ARROW = 133;
  /** RegularExpression Id. */
  int LPAREN = 134;
  /** RegularExpression Id. */
  int RPAREN = 135;
  /** RegularExpression Id. */
  int LBRACE = 136;
  /** RegularExpression Id. */
  int RBRACE = 137;
  /** RegularExpression Id. */
  int LBRACKET = 138;
  /** RegularExpression Id. */
  int RBRACKET = 139;
  /** RegularExpression Id. */
  int COMMA = 140;
  /** RegularExpression Id. */
  int DOT = 141;
  /** RegularExpression Id. */
  int SEMI = 142;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 143;
  /** RegularExpression Id. */
  int ELLIPSIS = 144;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<COMMENT_BLOCK>",
    "<LINE_COMMENT>",
    "\"#if\"",
    "\"#else\"",
    "\"#endif\"",
    "\"#region\"",
    "\"#endregion\"",
    "\"#line\"",
    "\"#error\"",
    "\"#warning\"",
    "\"#define\"",
    "\"#undef\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<BINARY_INTEGER>",
    "<DECIMAL_INTEGER>",
    "<HEXADECIMAL_INTEGER>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<SIMPLE_ID>",
    "<ESCAPED_ID>",
    "<ID>",
    "<ASCII_ESCAPE>",
    "<HEX_ESCAPE>",
    "<OCTAL_ESCAPE>",
    "<UNICODE4>",
    "<UNICODE8>",
    "<VERBATIM_STRING>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"?.\"",
    "\"??\"",
    "\"=>\"",
    "\"++\"",
    "\"--\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"::\"",
    "\"...\"",
  };

}
