/* Generated By:JavaCC: Do not edit this line. lexico_csharpTokenManager.java */
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.HashMap;

/** Token Manager. */
public class lexico_csharpTokenManager implements lexico_csharpConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffff1c0000L) != 0L || (active1 & 0x3ffffffffL) != 0L)
         {
            jjmatchedKind = 98;
            return 64;
         }
         if ((active1 & 0x800000000000L) != 0L)
            return 38;
         return -1;
      case 1:
         if ((active0 & 0xf05ffcfffd1c0000L) != 0L || (active1 & 0x3ffffffffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return 64;
         }
         if ((active0 & 0xfa0030002000000L) != 0L)
            return 64;
         return -1;
      case 2:
         if ((active0 & 0x7053fefffd1c0000L) != 0L || (active1 & 0x3ffbffdfbL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return 64;
         }
         if ((active0 & 0x870c000000000000L) != 0L || (active1 & 0x400204L) != 0L)
            return 64;
         return -1;
      case 3:
         if ((active0 & 0x464bf2fe91080000L) != 0L || (active1 & 0x37eaffdfbL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 3;
            return 64;
         }
         if ((active0 & 0x30100c016c140000L) != 0L || (active1 & 0x81100000L) != 0L)
            return 64;
         return -1;
      case 4:
         if ((active0 & 0x4648e2f201000000L) != 0L || (active1 & 0x15c8fd5fbL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 4;
            return 64;
         }
         if ((active0 & 0x3100c90080000L) != 0L || (active1 & 0x222202800L) != 0L)
            return 64;
         return -1;
      case 5:
         if ((active0 & 0x4648a0f201000000L) != 0L || (active1 & 0x14400816aL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 5;
            return 64;
         }
         if ((active0 & 0x420000000000L) != 0L || (active1 & 0x188f5491L) != 0L)
            return 64;
         return -1;
      case 6:
         if ((active0 & 0x8806200000000L) != 0L || (active1 & 0x40000020L) != 0L)
            return 64;
         if ((active0 & 0x4640209001000000L) != 0L || (active1 & 0x10400814aL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 6;
            return 64;
         }
         return -1;
      case 7:
         if ((active0 & 0x4200000000000000L) != 0L || (active1 & 0x4008040L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 7;
            return 64;
         }
         if ((active0 & 0x440209001000000L) != 0L || (active1 & 0x10000010aL) != 0L)
            return 64;
         return -1;
      case 8:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 8;
            return 64;
         }
         if ((active0 & 0x4200000000000000L) != 0L || (active1 & 0x4000040L) != 0L)
            return 64;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 121;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000000L, 0x0L);
      case 35:
         return jjMoveStringLiteralDfa1_0(0x3ff00L, 0x0L, 0x0L);
      case 38:
         jjmatchedKind = 122;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 134);
      case 41:
         return jjStopAtPos(0, 135);
      case 42:
         return jjStopAtPos(0, 110);
      case 43:
         jjmatchedKind = 108;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x8L);
      case 44:
         return jjStopAtPos(0, 140);
      case 45:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x30L);
      case 46:
         jjmatchedKind = 141;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10000L);
      case 47:
         return jjStartNfaWithStates_0(0, 111, 38);
      case 58:
         jjmatchedKind = 127;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x8000L);
      case 59:
         return jjStopAtPos(0, 142);
      case 60:
         jjmatchedKind = 115;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000000000000L, 0x0L);
      case 61:
         jjmatchedKind = 112;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000000L, 0x4L);
      case 62:
         jjmatchedKind = 116;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40000000000000L, 0x0L);
      case 63:
         jjmatchedKind = 126;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x3L);
      case 91:
         return jjStopAtPos(0, 138);
      case 93:
         return jjStopAtPos(0, 139);
      case 94:
         return jjStopAtPos(0, 124);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x3000000L, 0x0L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x3c000000L, 0x0L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1fc0000000L, 0x0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3e000000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x7c0000000000L, 0x0L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xf800000080000L, 0x0L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x10000000000000L, 0x0L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0xfe0000000000000L, 0x0L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x3000000000000000L, 0x0L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0xc000000000100000L, 0x0L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xfL, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xf0L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x700L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xff800L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0xf00000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3f000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1c0000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 136);
      case 124:
         jjmatchedKind = 123;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 137);
      case 126:
         return jjStopAtPos(0, 125);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 119);
         break;
      case 43:
         if ((active2 & 0x8L) != 0L)
            return jjStopAtPos(1, 131);
         break;
      case 45:
         if ((active2 & 0x10L) != 0L)
            return jjStopAtPos(1, 132);
         break;
      case 46:
         if ((active2 & 0x1L) != 0L)
            return jjStopAtPos(1, 128);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x10000L);
      case 58:
         if ((active2 & 0x8000L) != 0L)
            return jjStopAtPos(1, 143);
         break;
      case 61:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 113);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 114);
         else if ((active1 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 117);
         else if ((active1 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 118);
         break;
      case 62:
         if ((active2 & 0x4L) != 0L)
            return jjStopAtPos(1, 130);
         else if ((active2 & 0x20L) != 0L)
            return jjStopAtPos(1, 133);
         break;
      case 63:
         if ((active2 & 0x2L) != 0L)
            return jjStopAtPos(1, 129);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000c4080000L, active1, 0x10L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0x801L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000e000005600L, active1, 0x1700L, active2, 0L);
      case 102:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 53, 64);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x300000000L, active1, 0x200302000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000000100L, active1, 0x41004000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x2040400002000L, active1, 0x2000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 110:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x700080000000000L, active1, 0xc000000L, active2, 0L);
      case 111:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x301c021808000000L, active1, 0x180000000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x10040800L, active1, 0x400060L, active2, 0L);
      case 115:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(1, 25, 64);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 59, 64);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x30000000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x78000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x120000L, active1, 0x84L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L, active1, 0x8L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L, active1, 0x80000L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x600000000000L, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0x800000L, active2, 0L);
      case 124:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 120);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active2 & 0x10000L) != 0L)
            return jjStopAtPos(2, 144);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x500008000L, active1, 0x19100L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000002000000000L, active1, 0x4000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x100210010800L, active1, 0xaL, active2, 0L);
      case 102:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(2, 8);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 64);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L, active1, 0x2a0180020L, active2, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000180200L, active1, 0x100000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000000L, active1, 0L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000801800021400L, active1, 0x1000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000008000000L, active1, 0x2002040L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40200000000000L, active1, 0x800000L, active2, 0L);
      case 114:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000004000L, active1, 0x40260010L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x40045000000L, active1, 0x8000000L, active2, 0L);
      case 116:
         if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(2, 66, 64);
         return jjMoveStringLiteralDfa3_0(active0, 0x6104000a0000000L, active1, 0x400L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0000040000L, active1, 0L, active2, 0L);
      case 119:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 63, 64);
         break;
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 86, 64);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L, active2, 0L);
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x2804010000000L, active1, 0x108000010L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x280000000L, active1, 0x8000L);
      case 100:
         if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 95, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0x21400L, active1, 0x100L);
      case 101:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 64);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 64);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 64);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 64);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 42, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0x4609408000000000L, active1, 0x804001L);
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L, active1, 0L);
      case 103:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 61, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0x800L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L, active1, 0x20000L);
      case 107:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 60, 64);
         break;
      case 108:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 64);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 27, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0x40200000000000L, active1, 0x200001080L);
      case 109:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 43, 64);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000002000L, active1, 0x22000000L);
      case 111:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x10200000L);
      case 114:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0xc000L, active1, 0x200aL);
      case 115:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 84, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0xc00080200L, active1, 0L);
      case 116:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 88, 64);
         return jjMoveStringLiteralDfa4_0(active0, 0x1001000000L, active1, 0x40090840L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40400L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0x22L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xc0001L);
      case 100:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 48, 64);
         break;
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(4, 9);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(4, 13);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 19, 64);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 75, 64);
         else if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 97, 64);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L, active1, 0x4001040L);
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000000L);
      case 103:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 89, 64);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 93, 64);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L, active1, 0L);
      case 104:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 64);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40201000010c00L, active1, 0x10080L);
      case 107:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 64);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L, active1, 0x8000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x820000000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L, active1, 0x10L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L, active1, 0x20000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L, active1, 0x804100L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x600400001001000L, active1, 0x10000408L);
      case 115:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 64);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0L);
      case 116:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 64);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 44, 64);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 49, 64);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 77, 64);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x100000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L, active1, 0x40000000L);
      case 119:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 85, 64);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0xa001000000L, active1, 0x40008000L);
      case 99:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 71, 64);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(5, 80, 64);
         return jjMoveStringLiteralDfa6_0(active0, 0x48200000000000L, active1, 0x4000040L);
      case 100:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 76, 64);
         break;
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 41, 64);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 91, 64);
         return jjMoveStringLiteralDfa6_0(active0, 0x200001000L, active1, 0L);
      case 102:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(5, 10);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(5, 17);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 64);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 87, 64);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000000000L, active1, 0L);
      case 103:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 81, 64);
         break;
      case 104:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(5, 83, 64);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L, active1, 0x100000008L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x804000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 46, 64);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 74, 64);
         return jjMoveStringLiteralDfa6_0(active0, 0x400001000010000L, active1, 0x100L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(5, 14);
         break;
      case 115:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(5, 68, 64);
         break;
      case 116:
         if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(5, 64, 64);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 82, 64);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(5, 92, 64);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x22L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x4600000000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L, active1, 0L);
      case 100:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 64);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(6, 16);
         else if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 64);
         break;
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L, active1, 0L);
      case 104:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 51, 64);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x40200000000000L, active1, 0L);
      case 107:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4000000L);
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 37, 64);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 94, 64);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100008100L);
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(6, 11);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2L);
      case 116:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 64);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000L, active1, 0x40L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0L);
      case 121:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 64);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x4200000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 64);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 39, 64);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(7, 67, 64);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 96, 64);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x4000040L);
      case 103:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(7, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L, active1, 0L);
      case 108:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 58, 64);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x8000L);
      case 114:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 65, 64);
         break;
      case 116:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(7, 24, 64);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 45, 64);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 54, 64);
         break;
      case 121:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 72, 64);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 70, 64);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(8, 90, 64);
         break;
      case 101:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 57, 64);
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 62, 64);
         break;
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000L, active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 99:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(9, 79, 64);
         break;
      case 110:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(9, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 64;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                     jjCheckNAdd(58);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 98)
                        kind = 98;
                     jjCheckNAdd(57);
                  }
                  break;
               case 38:
                  if (curChar == 47)
                  {
                     if (kind > 7)
                        kind = 7;
                     jjCheckNAdd(44);
                  }
                  else if (curChar == 42)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 0:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(0, 4);
                  }
                  else if (curChar == 48)
                     jjAddStates(5, 6);
                  else if (curChar == 47)
                     jjAddStates(7, 8);
                  else if (curChar == 34)
                     jjCheckNAddStates(9, 12);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddStates(0, 4);
                  break;
               case 8:
                  if (curChar == 34)
                     jjCheckNAddStates(13, 15);
                  break;
               case 9:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 10:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 11:
                  if (curChar == 34 && kind > 106)
                     kind = 106;
                  break;
               case 13:
                  if (curChar == 34)
                     jjCheckNAddStates(9, 12);
                  break;
               case 14:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 15:
                  if (curChar == 34 && kind > 107)
                     kind = 107;
                  break;
               case 17:
                  if ((0x1008400000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(16, 20);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 34:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(21, 25);
                  break;
               case 35:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(26, 30);
                  break;
               case 36:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 37:
                  if (curChar == 47)
                     jjAddStates(7, 8);
                  break;
               case 39:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if (curChar == 42)
                     jjAddStates(31, 32);
                  break;
               case 41:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 42:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 43:
                  if (curChar != 47)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(44);
                  break;
               case 44:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(44);
                  break;
               case 45:
                  if (curChar == 48)
                     jjAddStates(5, 6);
                  break;
               case 47:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjAddStates(33, 37);
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjCheckNAdd(57);
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAdd(58);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjstateSet[jjnewStateCnt++] = 63;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 64:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 100)
                        kind = 100;
                     jjCheckNAdd(58);
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 98)
                        kind = 98;
                     jjCheckNAdd(57);
                  }
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 98)
                        kind = 98;
                     jjCheckNAddTwoStates(57, 58);
                  }
                  else if (curChar == 64)
                     jjAddStates(38, 39);
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 2:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjAddStates(40, 42);
                  break;
               case 3:
                  if ((0x100000001000L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 4:
                  if (curChar == 76 && kind > 22)
                     kind = 22;
                  break;
               case 5:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 108 && kind > 22)
                     kind = 22;
                  break;
               case 7:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  jjAddStates(13, 15);
                  break;
               case 12:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 14:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 16:
                  if (curChar == 92)
                     jjAddStates(43, 44);
                  break;
               case 17:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 18:
                  if (curChar == 92)
                     jjAddStates(45, 47);
                  break;
               case 19:
                  if (curChar == 120)
                     jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(16, 20);
                  break;
               case 21:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 26:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 39:
               case 41:
                  jjCheckNAddTwoStates(39, 40);
                  break;
               case 44:
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 48:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(49);
                  break;
               case 49:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjCheckNAddStates(33, 37);
                  break;
               case 50:
                  if ((0x20000000200000L & l) == 0L)
                     break;
                  if (kind > 23)
                     kind = 23;
                  jjCheckNAddStates(48, 50);
                  break;
               case 51:
                  if ((0x100000001000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 52:
                  if (curChar == 76 && kind > 23)
                     kind = 23;
                  break;
               case 53:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 108 && kind > 23)
                     kind = 23;
                  break;
               case 55:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjCheckNAddTwoStates(57, 58);
                  break;
               case 57:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjCheckNAdd(57);
                  break;
               case 58:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAdd(58);
                  break;
               case 59:
                  if (curChar == 64)
                     jjAddStates(38, 39);
                  break;
               case 60:
               case 61:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjCheckNAdd(61);
                  break;
               case 62:
               case 63:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 100)
                     kind = 100;
                  jjCheckNAdd(63);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(13, 15);
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(9, 12);
                  break;
               case 39:
               case 41:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjstateSet[jjnewStateCnt++] = 44;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 64 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 2, 3, 5, 7, 46, 48, 38, 43, 14, 15, 16, 18, 9, 10, 11, 
   14, 20, 15, 16, 18, 14, 15, 16, 18, 35, 14, 36, 15, 16, 18, 41, 
   42, 49, 50, 51, 53, 55, 60, 62, 3, 5, 7, 17, 34, 19, 21, 26, 
   51, 53, 55, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\43\151\146", 
"\43\145\154\163\145", "\43\145\156\144\151\146", "\43\162\145\147\151\157\156", 
"\43\145\156\144\162\145\147\151\157\156", "\43\154\151\156\145", "\43\145\162\162\157\162", 
"\43\167\141\162\156\151\156\147", "\43\144\145\146\151\156\145", "\43\165\156\144\145\146", "\164\162\165\145", 
"\146\141\154\163\145", "\156\165\154\154", null, null, null, "\141\142\163\164\162\141\143\164", 
"\141\163", "\142\141\163\145", "\142\157\157\154", "\142\162\145\141\153", 
"\142\171\164\145", "\143\141\163\145", "\143\141\164\143\150", "\143\150\141\162", 
"\143\150\145\143\153\145\144", "\143\154\141\163\163", "\143\157\156\163\164", 
"\143\157\156\164\151\156\165\145", "\144\145\143\151\155\141\154", "\144\145\146\141\165\154\164", 
"\144\145\154\145\147\141\164\145", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\145\156\165\155", "\145\166\145\156\164", "\145\170\160\154\151\143\151\164", 
"\145\170\164\145\162\156", "\146\151\156\141\154\154\171", "\146\151\170\145\144", 
"\146\154\157\141\164", "\146\157\162", "\146\157\162\145\141\143\150", "\147\157\164\157", 
"\151\146", "\151\155\160\154\151\143\151\164", "\151\156", "\151\156\164", 
"\151\156\164\145\162\146\141\143\145", "\151\156\164\145\162\156\141\154", "\151\163", "\154\157\143\153", 
"\154\157\156\147", "\156\141\155\145\163\160\141\143\145", "\156\145\167", 
"\157\142\152\145\143\164", "\157\160\145\162\141\164\157\162", "\157\165\164", 
"\157\166\145\162\162\151\144\145", "\160\141\162\141\155\163", "\160\162\151\166\141\164\145", 
"\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", "\162\145\141\144\157\156\154\171", 
"\162\145\146", "\162\145\164\165\162\156", "\163\142\171\164\145", 
"\163\145\141\154\145\144", "\163\150\157\162\164", "\163\151\172\145\157\146", 
"\163\164\141\143\153\141\154\154\157\143", "\163\164\141\164\151\143", "\163\164\162\151\156\147", 
"\163\164\162\165\143\164", "\163\167\151\164\143\150", "\164\150\151\163", "\164\150\162\157\167", 
"\164\162\171", "\164\171\160\145\157\146", "\165\151\156\164", "\165\154\157\156\147", 
"\165\156\143\150\145\143\153\145\144", "\165\156\163\141\146\145", "\165\163\150\157\162\164", 
"\165\163\151\156\147", "\166\151\162\164\165\141\154", "\166\157\151\144", 
"\166\157\154\141\164\151\154\145", "\167\150\151\154\145", null, null, null, null, null, null, null, null, null, 
null, "\53", "\55", "\52", "\57", "\75", "\75\75", "\41\75", "\74", "\76", "\74\75", 
"\76\75", "\46\46", "\174\174", "\41", "\46", "\174", "\136", "\176", "\77", "\72", 
"\77\56", "\77\77", "\75\76", "\53\53", "\55\55", "\55\76", "\50", "\51", "\173", 
"\175", "\133", "\135", "\54", "\56", "\73", "\72\72", "\56\56\56", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0xfffffc1fffffffffL, 0x1ffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[64];
static private final int[] jjstateSet = new int[128];
static protected char curChar;
/** Constructor. */
public lexico_csharpTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public lexico_csharpTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 64; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
