/* Generated By:JavaCC: Do not edit this line. lexico_csharpConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface lexico_csharpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 6;
  /** RegularExpression Id. */
  int LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int XML_COMMENT = 8;
  /** RegularExpression Id. */
  int PRE_IF = 9;
  /** RegularExpression Id. */
  int PRE_ELSE = 10;
  /** RegularExpression Id. */
  int PRE_ENDIF = 11;
  /** RegularExpression Id. */
  int PRE_REGION = 12;
  /** RegularExpression Id. */
  int PRE_ENDREGION = 13;
  /** RegularExpression Id. */
  int PRE_LINE = 14;
  /** RegularExpression Id. */
  int PRE_ERROR = 15;
  /** RegularExpression Id. */
  int PRE_WARNING = 16;
  /** RegularExpression Id. */
  int PRE_DEFINE = 17;
  /** RegularExpression Id. */
  int PRE_UNDEF = 18;
  /** RegularExpression Id. */
  int TRUE = 19;
  /** RegularExpression Id. */
  int FALSE = 20;
  /** RegularExpression Id. */
  int NULL = 21;
  /** RegularExpression Id. */
  int BINARY_INTEGER = 22;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER = 23;
  /** RegularExpression Id. */
  int HEXADECIMAL_INTEGER = 24;
  /** RegularExpression Id. */
  int ABSTRACT = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int BASE = 27;
  /** RegularExpression Id. */
  int BOOL = 28;
  /** RegularExpression Id. */
  int BREAK = 29;
  /** RegularExpression Id. */
  int BYTE = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int CATCH = 32;
  /** RegularExpression Id. */
  int CHAR = 33;
  /** RegularExpression Id. */
  int CHECKED = 34;
  /** RegularExpression Id. */
  int CLASS = 35;
  /** RegularExpression Id. */
  int CONST = 36;
  /** RegularExpression Id. */
  int CONTINUE = 37;
  /** RegularExpression Id. */
  int DECIMAL = 38;
  /** RegularExpression Id. */
  int KWDEFAULT = 39;
  /** RegularExpression Id. */
  int DELEGATE = 40;
  /** RegularExpression Id. */
  int DO = 41;
  /** RegularExpression Id. */
  int DOUBLE = 42;
  /** RegularExpression Id. */
  int ELSE = 43;
  /** RegularExpression Id. */
  int ENUM = 44;
  /** RegularExpression Id. */
  int EVENT = 45;
  /** RegularExpression Id. */
  int EXPLICIT = 46;
  /** RegularExpression Id. */
  int EXTERN = 47;
  /** RegularExpression Id. */
  int FINALLY = 48;
  /** RegularExpression Id. */
  int FIXED = 49;
  /** RegularExpression Id. */
  int FLOAT = 50;
  /** RegularExpression Id. */
  int FOR = 51;
  /** RegularExpression Id. */
  int FOREACH = 52;
  /** RegularExpression Id. */
  int GOTO = 53;
  /** RegularExpression Id. */
  int IF = 54;
  /** RegularExpression Id. */
  int IMPLICIT = 55;
  /** RegularExpression Id. */
  int IN = 56;
  /** RegularExpression Id. */
  int INT = 57;
  /** RegularExpression Id. */
  int INTERFACE = 58;
  /** RegularExpression Id. */
  int INTERNAL = 59;
  /** RegularExpression Id. */
  int IS = 60;
  /** RegularExpression Id. */
  int LOCK = 61;
  /** RegularExpression Id. */
  int LONG = 62;
  /** RegularExpression Id. */
  int NAMESPACE = 63;
  /** RegularExpression Id. */
  int NEW = 64;
  /** RegularExpression Id. */
  int OBJECT = 65;
  /** RegularExpression Id. */
  int OPERATOR = 66;
  /** RegularExpression Id. */
  int OUT = 67;
  /** RegularExpression Id. */
  int OVERRIDE = 68;
  /** RegularExpression Id. */
  int PARAMS = 69;
  /** RegularExpression Id. */
  int PRIVATE = 70;
  /** RegularExpression Id. */
  int PROTECTED = 71;
  /** RegularExpression Id. */
  int PUBLIC = 72;
  /** RegularExpression Id. */
  int READONLY = 73;
  /** RegularExpression Id. */
  int REF = 74;
  /** RegularExpression Id. */
  int RETURN = 75;
  /** RegularExpression Id. */
  int SBYTE = 76;
  /** RegularExpression Id. */
  int SEALED = 77;
  /** RegularExpression Id. */
  int SHORT = 78;
  /** RegularExpression Id. */
  int SIZEOF = 79;
  /** RegularExpression Id. */
  int STACKALLOC = 80;
  /** RegularExpression Id. */
  int STATIC = 81;
  /** RegularExpression Id. */
  int STRING = 82;
  /** RegularExpression Id. */
  int STRUCT = 83;
  /** RegularExpression Id. */
  int SWITCH = 84;
  /** RegularExpression Id. */
  int THIS = 85;
  /** RegularExpression Id. */
  int THROW = 86;
  /** RegularExpression Id. */
  int TRY = 87;
  /** RegularExpression Id. */
  int TYPEOF = 88;
  /** RegularExpression Id. */
  int UINT = 89;
  /** RegularExpression Id. */
  int ULONG = 90;
  /** RegularExpression Id. */
  int UNCHECKED = 91;
  /** RegularExpression Id. */
  int UNSAFE = 92;
  /** RegularExpression Id. */
  int USHORT = 93;
  /** RegularExpression Id. */
  int USING = 94;
  /** RegularExpression Id. */
  int VIRTUAL = 95;
  /** RegularExpression Id. */
  int VOID = 96;
  /** RegularExpression Id. */
  int VOLATILE = 97;
  /** RegularExpression Id. */
  int WHILE = 98;
  /** RegularExpression Id. */
  int ID = 99;
  /** RegularExpression Id. */
  int ASCII_ESCAPE = 100;
  /** RegularExpression Id. */
  int HEX_ESCAPE = 101;
  /** RegularExpression Id. */
  int OCTAL_ESCAPE = 102;
  /** RegularExpression Id. */
  int UNICODE4 = 103;
  /** RegularExpression Id. */
  int UNICODE8 = 104;
  /** RegularExpression Id. */
  int VERBATIM_STRING = 105;
  /** RegularExpression Id. */
  int STRING_LITERAL = 106;
  /** RegularExpression Id. */
  int PLUS = 107;
  /** RegularExpression Id. */
  int MINUS = 108;
  /** RegularExpression Id. */
  int MULT = 109;
  /** RegularExpression Id. */
  int DIV = 110;
  /** RegularExpression Id. */
  int ASSIGN = 111;
  /** RegularExpression Id. */
  int EQ = 112;
  /** RegularExpression Id. */
  int NEQ = 113;
  /** RegularExpression Id. */
  int LT = 114;
  /** RegularExpression Id. */
  int GT = 115;
  /** RegularExpression Id. */
  int LTE = 116;
  /** RegularExpression Id. */
  int GTE = 117;
  /** RegularExpression Id. */
  int AND = 118;
  /** RegularExpression Id. */
  int OR = 119;
  /** RegularExpression Id. */
  int NOT = 120;
  /** RegularExpression Id. */
  int BITAND = 121;
  /** RegularExpression Id. */
  int BITOR = 122;
  /** RegularExpression Id. */
  int BITXOR = 123;
  /** RegularExpression Id. */
  int BITNOT = 124;
  /** RegularExpression Id. */
  int QUESTION = 125;
  /** RegularExpression Id. */
  int COLON = 126;
  /** RegularExpression Id. */
  int NULL_COND = 127;
  /** RegularExpression Id. */
  int NULL_COALESCE = 128;
  /** RegularExpression Id. */
  int LAMBDA = 129;
  /** RegularExpression Id. */
  int INCR = 130;
  /** RegularExpression Id. */
  int DECR = 131;
  /** RegularExpression Id. */
  int ARROW = 132;
  /** RegularExpression Id. */
  int LPAREN = 133;
  /** RegularExpression Id. */
  int RPAREN = 134;
  /** RegularExpression Id. */
  int LBRACE = 135;
  /** RegularExpression Id. */
  int RBRACE = 136;
  /** RegularExpression Id. */
  int LBRACKET = 137;
  /** RegularExpression Id. */
  int RBRACKET = 138;
  /** RegularExpression Id. */
  int COMMA = 139;
  /** RegularExpression Id. */
  int DOT = 140;
  /** RegularExpression Id. */
  int SEMI = 141;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 142;
  /** RegularExpression Id. */
  int ELLIPSIS = 143;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\"",
    "<COMMENT_BLOCK>",
    "<LINE_COMMENT>",
    "<XML_COMMENT>",
    "\"#if\"",
    "\"#else\"",
    "\"#endif\"",
    "\"#region\"",
    "\"#endregion\"",
    "\"#line\"",
    "\"#error\"",
    "\"#warning\"",
    "\"#define\"",
    "\"#undef\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<BINARY_INTEGER>",
    "<DECIMAL_INTEGER>",
    "<HEXADECIMAL_INTEGER>",
    "\"abstract\"",
    "\"as\"",
    "\"base\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"checked\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"decimal\"",
    "\"default\"",
    "\"delegate\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"explicit\"",
    "\"extern\"",
    "\"finally\"",
    "\"fixed\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"goto\"",
    "\"if\"",
    "\"implicit\"",
    "\"in\"",
    "\"int\"",
    "\"interface\"",
    "\"internal\"",
    "\"is\"",
    "\"lock\"",
    "\"long\"",
    "\"namespace\"",
    "\"new\"",
    "\"object\"",
    "\"operator\"",
    "\"out\"",
    "\"override\"",
    "\"params\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"readonly\"",
    "\"ref\"",
    "\"return\"",
    "\"sbyte\"",
    "\"sealed\"",
    "\"short\"",
    "\"sizeof\"",
    "\"stackalloc\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"switch\"",
    "\"this\"",
    "\"throw\"",
    "\"try\"",
    "\"typeof\"",
    "\"uint\"",
    "\"ulong\"",
    "\"unchecked\"",
    "\"unsafe\"",
    "\"ushort\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<ID>",
    "<ASCII_ESCAPE>",
    "<HEX_ESCAPE>",
    "<OCTAL_ESCAPE>",
    "<UNICODE4>",
    "<UNICODE8>",
    "<VERBATIM_STRING>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"?.\"",
    "\"??\"",
    "\"=>\"",
    "\"++\"",
    "\"--\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"::\"",
    "\"...\"",
  };

}
